### ISSUE TITLE
大佬您好，我这配置完环境运行main.py后报错，大佬能看看嘛

### ISSUE THREAD

**Issue by Furxier** [Xie-Tiao/Limbus-Scripts#1]
D:\anaconda3\python.exe E:\XmpCache\LBclicker2.2.1\main.py 
Unhandled error processing page session : Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\flet\flet.py", line 316, in on_session_created
    session_handler(page)
  File "E:\XmpCache\LBclicker2.2.1\main.py", line 51, in main
    MainWork()
  File "E:\XmpCache\LBclicker2.2.1\workbench\mainwork.py", line 47, in MainWork
    piccheck = checkpic(pic)
  File "E:\XmpCache\LBclicker2.2.1\workbench\mainwork.py", line 24, in checkpic
    if locateOnScreen('./assets/'+pic,confidence=0.9) is not None:
TypeError: _couldNotImportPyScreeze() got an unexpected keyword argument 'confidence'
环境是python3.10

**Comment by Xie-Tiao** [comment]
就你的报错来看，你确定环境配置好了？倒数第二行看起来像是pyautogui库没装呢？

**Comment by Furxier** [comment]
装了PyAutoGUI                     0.9.50

**Comment by Xie-Tiao** [comment]
我想起来了，高版本的python用这个库是会出这个问题，有两个解决方法：
- 要么试试升级一下**pytutogui** => `pip install --upgrade pyautogui`
- 要么用跟我一样的版本吧**python 3.9.13**

如果都不行，那就等我优化吧。
----
*PS：顺便有点好奇你怎么找到这脚本的？我应该还没在任何平台宣传过吧* 😳

**Comment by Furxier** [comment]
哈哈哈，因为我是直接在Github上搜limbuscompany来看看有没有开源脚本用的，我自己肝了一天镜像，觉得这游戏必有脚本.

**Comment by Furxier** [comment]
ok，能更新pytutogui之后能用了

**Comment by Furxier** [comment]
喜欢大佬能整一个自动下镜本的，这玩意真折磨.
