### ISSUE TITLE
一个本地报错,请求解惑

### ISSUE THREAD

**Issue by Strairyter** [Xie-Tiao/Limbus-Scripts#3]
在配置环境后运行main.py的问题
Unhandled error processing page session : Traceback(most recent call last):
......
File "D:\LBclicker2.3.3\workbench\mainwork. py", line 24, in checkpic
if pyautogui.locateOnScreen('./assets/'+pic, confidence=0.9) is not None :
TypeError: _couldNotImportPyScreeze() got an unexpected keyword argument 'confidence'

**Comment by Xie-Tiao** [comment]
之前有位朋友跟你类似的问题，参考一下https://github.com/Xie-Tiao/Limbus-Scripts/issues/1

**Comment by Strairyter** [comment]
问题已解决，十分感谢
